// Vortex Downloader - Background Service Worker
chrome.runtime.onInstalled.addListener(() => {
    console.log("Vortex Downloader Integration Module đã được cài đặt thành công!");
    syncCookiesToGateway();
});

// Chuyển đổi mảng cookie sang định dạng Netscape cookie file chuẩn
function cookiesToNetscape(cookies) {
    if (!cookies || !cookies.length) return "";
    let lines = [
        "# Netscape HTTP Cookie File",
        "# http://curl.haxx.se/rfc/cookie_spec.html",
        "# This file was generated by Vortex Downloader",
        ""
    ];
    for (const c of cookies) {
        let domain = c.domain || "";
        if (!domain.startsWith(".") && !domain.startsWith("http")) {
            domain = "." + domain;
        }
        const includeSub = domain.startsWith(".") ? "TRUE" : "FALSE";
        const path = c.path || "/";
        const secure = c.secure ? "TRUE" : "FALSE";
        const expiry = c.expirationDate ? Math.floor(c.expirationDate) : Math.floor(Date.now() / 1000) + 31536000;
        const name = c.name;
        const value = c.value;
        lines.push(`${domain}\t${includeSub}\t${path}\t${secure}\t${expiry}\t${name}\t${value}`);
    }
    return lines.join("\n") + "\n";
}

// Lấy toàn bộ cookies của YouTube & Google
async function getYouTubeCookies() {
    return new Promise((resolve) => {
        try {
            if (!chrome.cookies) {
                console.warn("[Vortex] chrome.cookies API chưa sẵn sàng");
                resolve("");
                return;
            }
            const p1 = new Promise((res) => chrome.cookies.getAll({ url: "https://www.youtube.com" }, (c) => res(c || [])));
            const p2 = new Promise((res) => chrome.cookies.getAll({ domain: ".youtube.com" }, (c) => res(c || [])));
            const p3 = new Promise((res) => chrome.cookies.getAll({ domain: "youtube.com" }, (c) => res(c || [])));
            const p4 = new Promise((res) => chrome.cookies.getAll({ domain: ".google.com" }, (c) => res(c || [])));

            Promise.all([p1, p2, p3, p4]).then((results) => {
                const cookieMap = new Map();
                for (const list of results) {
                    for (const c of list) {
                        const key = `${c.domain}#${c.name}#${c.path}`;
                        cookieMap.set(key, c);
                    }
                }
                const combined = Array.from(cookieMap.values());
                console.log(`[Vortex Background] Đã lấy ${combined.length} cookies YouTube/Google`);
                resolve(cookiesToNetscape(combined));
            }).catch((err) => {
                console.error("[Vortex Background] Lỗi khi lấy cookies:", err);
                resolve("");
            });
        } catch (e) {
            console.error("[Vortex Background] Exception:", e);
            resolve("");
        }
    });
}

// Tự động đồng bộ cookie lên Gateway backend khi có thể
async function syncCookiesToGateway() {
    try {
        const netscape = await getYouTubeCookies();
        if (netscape && netscape.length > 50) {
            await fetch("http://localhost:8000/api/v1/cookies/sync", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ cookies: netscape })
            });
        }
    } catch (e) {
        // Gateway chưa bật hoặc offline
    }
}

// Lắng nghe lệnh từ Content Script hoặc Popup nếu cần
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.type === "CHECK_GATEWAY") {
        fetch("http://localhost:8000/health")
            .then(res => res.json())
            .then(data => sendResponse({ online: true, data }))
            .catch(() => sendResponse({ online: false }));
        return true; // Cho phép async sendResponse
    }

    if (request.type === "GET_NETSCAPE_COOKIES") {
        getYouTubeCookies().then((netscape) => {
            sendResponse({ cookies: netscape });
            syncCookiesToGateway();
        });
        return true;
    }
});
